const EVENT_CATEGORY_LABELS = {
  onsite: '현장이벤트',
  cinetalk: '씨네토크',
  preview: '시사회',
  other: '기타이벤트',
  past: '지난이벤트',
};

const EVENT_ITEMS = [
  {
    id: 1,
    category: 'onsite',
    period: '26.06.25 - 26.06.29',
    periodFull: '2026.06.25 - 2026.06.29',
    views: 144,
    title: '<유레카> 씨네큐브 마지막 상영 오리지널 포스터 (Beach) 증정',
    tags: ['현장이벤트', '선착순'],
    schedule: ['6월 29일 (월) 오후 7시', 'YSCine 2관'],
    paragraphs: [
      '영화 <유레카>의 마지막 상영이 6월 29일(월) 오후 7시 YSCine 2관에서 진행됩니다.',
      '마지막 상영에 참여하시는 관람객 분들께는 오리지널 포스터(Beach)를 선착순으로 증정해 드립니다. 소진 시 조기 종료될 수 있으니 참고 부탁드립니다.',
    ],
    posterUrl: null,
  },
  {
    id: 2,
    category: 'onsite',
    period: '26.06.25 - 26.06.29',
    periodFull: '2026.06.25 - 2026.06.29',
    views: 98,
    title: '<미지의 서울> 씨네큐브 마지막 상영 오리지널 포스터 (Beach) 증정',
    tags: ['현장이벤트', '선착순'],
    schedule: ['6월 28일 (일) 오후 4시', 'YSCine 1관'],
    paragraphs: [
      '<미지의 서울> 마지막 상영과 함께 진행되는 현장 이벤트입니다.',
      '상영 종료 후 관람객 대상으로 오리지널 포스터를 선착순 증정합니다.',
    ],
    posterUrl: null,
  },
  {
    id: 3,
    category: 'onsite',
    period: '26.06.25 - 26.06.29',
    periodFull: '2026.06.25 - 2026.06.29',
    views: 76,
    title: '<신명> 씨네큐브 마지막 상영 오리지널 포스터 (Beach) 증정',
    tags: ['현장이벤트', '선착순'],
    schedule: ['6월 27일 (토) 오후 8시', 'YSCine 3관'],
    paragraphs: [
      '<신명> 마지막 상영 회차에 참여하신 분들께 기념 포스터를 드립니다.',
      '이벤트는 당일 현장 수량 소진 시 종료됩니다.',
    ],
    posterUrl: null,
  },
  {
    id: 4,
    category: 'onsite',
    period: '26.06.25 - 26.06.29',
    periodFull: '2026.06.25 - 2026.06.29',
    views: 62,
    title: '<파과> 씨네큐브 마지막 상영 오리지널 포스터 (Beach) 증정',
    tags: ['현장이벤트', '선착순'],
    schedule: ['6월 26일 (금) 오후 9시', 'YSCine 2관'],
    paragraphs: [
      '<파과> 마지막 상영 이벤트에 많은 참여 부탁드립니다.',
      '관람 후 로비에서 포스터를 수령하실 수 있습니다.',
    ],
    posterUrl: null,
  },
  {
    id: 5,
    category: 'preview',
    period: '26.06.20 - 26.06.30',
    periodFull: '2026.06.20 - 2026.06.30',
    views: 210,
    title: '<슈퍼맨> 개봉 기념 시사회',
    tags: ['시사회'],
    schedule: ['6월 25일 (수) 오후 7시 30분', 'YSCine 1관'],
    paragraphs: [
      '<슈퍼맨> 개봉을 앞두고 진행되는 시사회입니다.',
      '사전 예매 고객 대상으로 진행되며, 자세한 안내는 공지사항을 확인해 주세요.',
    ],
    posterUrl: null,
  },
  {
    id: 6,
    category: 'cinetalk',
    period: '26.07.01 - 26.07.15',
    periodFull: '2026.07.01 - 2026.07.15',
    views: 88,
    title: '<파리의 사생활> 감독과 함께하는 씨네토크',
    tags: ['씨네토크'],
    schedule: ['7월 5일 (토) 오후 2시', 'YSCine 2관'],
    paragraphs: [
      '상영 후 감독과의 대담이 이어지는 씨네토크 행사입니다.',
      '현장 질문 참여가 가능하며, 좌석은 선착순입니다.',
    ],
    posterUrl: null,
  },
  {
    id: 7,
    category: 'other',
    period: '26.07.01 - 26.07.31',
    periodFull: '2026.07.01 - 2026.07.31',
    views: 54,
    title: '여름 시즌 관람객 감사 이벤트',
    tags: ['기타이벤트'],
    schedule: ['7월 1일 (화) - 7월 31일 (목)', 'YSCine 전관'],
    paragraphs: [
      '여름 시즌을 맞아 관람객 분들께 감사의 마음을 전하는 이벤트입니다.',
      '기간 내 현장 방문 고객 대상으로 소정의 기념품을 드립니다.',
    ],
    posterUrl: null,
  },
  {
    id: 8,
    category: 'past',
    period: '26.05.01 - 26.05.31',
    periodFull: '2026.05.01 - 2026.05.31',
    views: 131,
    title: '<어쩔수가없다> 시사회 (종료)',
    tags: ['지난이벤트'],
    schedule: ['5월 20일 (화) 오후 7시', 'YSCine 1관'],
    paragraphs: [
      '종료된 지난 이벤트입니다.',
      '참여해 주신 모든 분들께 감사드립니다.',
    ],
    posterUrl: null,
  },
];
